server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #uri: file:///Users/wnstl/Desktop/SpringProject/inflearn/SpringCludeMSA/spring-config
          uri: https://github.com/wnstlr0615/spring-config-server
          #private ? ??? ?? ??
          #username:
          #password: