spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/msa
    username: '{cipher}5161f69c8f84c5f4e79caf5e38b751eddee688efeec9c561811fa7b109cb3bd5'
    password:
token:
  expiration_time: 8640000
  secret: user_token1111_changed
